Transform: AWS::Serverless-2016-10-31
Resources:
  Menus:
    Type: AWS::Serverless::Function
    Properties:
      Description:
        Fn::Sub:
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Menus
      CodeUri: Menus
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Events:
        Site8GETapimenus:
          Type: Api
          Properties:
            Path: /api/menus
            Method: GET
            RestApiId:
              Ref: Site8
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.Menus06145a21DepLayer
    Metadata:
      SamResourceId: Menus
  MenusLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${Menus}
  Site8:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub:
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Site8
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /api/menus:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Menus.Arn}/invocations
              responses: {}
          /api/bookmarks:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Bookmarks.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  Bookmarks:
    Type: AWS::Serverless::Function
    Properties:
      Description:
        Fn::Sub:
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Bookmarks
      CodeUri: Bookmarks
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Events:
        Site8GETapibookmarks:
          Type: Api
          Properties:
            Path: /api/bookmarks
            Method: GET
            RestApiId:
              Ref: Site8
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.Bookmarks7a69d6b2DepLayer
    Metadata:
      SamResourceId: Bookmarks
  BookmarksLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${Bookmarks}
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: C:\Users\jdumo\Documents\0Projects\site8\composer\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
