export type ICase = {
  caseNumber: string;
  caseStatus?: string;
  dateTimeOpened?: Date;
  delayReason?: string;
  deliveryDate?: string;
  deliveryWindowEnd?: Date;
  deliveryWindowStart?: Date;
  invoicedItemNumber?: string;
  invoicedItemQuantity?: number;
  invoicedUnit?: string;
  invoiceNumber?: string;
  issueType?: string;
  itemCodes?: string[];
  pack?: string;
  paperworkType?: string;
  quantityReported?: number;
  requesterFirstName?: string;
  requesterLastName?: string;
  requestType?: string;
  revisedDeliveryWindowEnd?: string;
  revisedDeliveryWindowStart?: string;
  routeNumber?: string;
  unit?: string;
};
